spring:
  profiles: local
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      database-platform: org.hibernate.dialect.MariaDB103Dialect
      ddl-auto: none
    properties:
      format_sql: true
  data: 
    mongodb: 
      uri: mongodb://127.0.0.1

management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      cors:
        allowed-methods: GET,POST
      exposure:
        include: '*'
  health:
    diskspace:
      enabled: true

logging : 
  level :     
    org : 
      hibernate : 
        type : 
          descriptor : 
            sql : TRACE