version: "3.7"
services:
  moviemang-mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: always
    ports:
      - "3206:3206"
    environment:
      - MYSQL_DATABASE=moviemang
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=moviemang
      - MYSQL_PASSWORD=moviemang-pass
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./mysql:/var/lib/mysql
  moviemang-mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=moviemang
      - MYSQL_ROOT_PASSWORD=root-pass
      - MYSQL_USER=moviemang
      - MYSQL_PASSWORD=moviemang-pass
      - TZ=Asia/Seoul
    command: # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --lower_case_table_names=1
    volumes:
      - ./maria/data:/var/lib/mysql
